// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkqUaKlj3gOI1dWbCeBCoq57oD-9kJfqw',
    appId: '1:182754780193:web:45e759a338e7c4347a2f60',
    messagingSenderId: '182754780193',
    projectId: 'intern-1c02f',
    authDomain: 'intern-1c02f.firebaseapp.com',
    storageBucket: 'intern-1c02f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAirYUawZH3dH_SG2g8sdVEXZXN_j3C9SQ',
    appId: '1:182754780193:android:986fc884e28093d47a2f60',
    messagingSenderId: '182754780193',
    projectId: 'intern-1c02f',
    storageBucket: 'intern-1c02f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwJajNFlDrrpCU07v1PS66UowNJ1TvNEg',
    appId: '1:182754780193:ios:e2695cf81a5e626f7a2f60',
    messagingSenderId: '182754780193',
    projectId: 'intern-1c02f',
    storageBucket: 'intern-1c02f.firebasestorage.app',
    iosBundleId: 'com.example.internFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwJajNFlDrrpCU07v1PS66UowNJ1TvNEg',
    appId: '1:182754780193:ios:e2695cf81a5e626f7a2f60',
    messagingSenderId: '182754780193',
    projectId: 'intern-1c02f',
    storageBucket: 'intern-1c02f.firebasestorage.app',
    iosBundleId: 'com.example.internFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkqUaKlj3gOI1dWbCeBCoq57oD-9kJfqw',
    appId: '1:182754780193:web:a41ccfcf7f7a53bb7a2f60',
    messagingSenderId: '182754780193',
    projectId: 'intern-1c02f',
    authDomain: 'intern-1c02f.firebaseapp.com',
    storageBucket: 'intern-1c02f.firebasestorage.app',
  );
}
